name: Mirror to GitVerse
on:
  push:
    branches: [ "master" ]
jobs:
  gitverse-mirroring:
    concurrency:
      group: ${{ github.workflow }}-gitverse
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare "https://github.com/$GITHUB_REPOSITORY" .
      - run: git push --mirror "https://gavrilovegor519:$GITVERSE_TOKEN@gitverse.ru/$GITHUB_REPOSITORY.git"
        env:
          GITVERSE_TOKEN: ${{ secrets.GITVERSE_TOKEN }}
